# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_constraints.xdc

# Block Designs: bd/led_test_system/led_test_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_test_system || ORIG_REF_NAME==led_test_system} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_led_controller_0_0/led_test_system_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_test_system_led_controller_0_0 || ORIG_REF_NAME==led_test_system_led_controller_0_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_test_system_processing_system7_0_0 || ORIG_REF_NAME==led_test_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_axi_smc_0/led_test_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_test_system_axi_smc_0 || ORIG_REF_NAME==led_test_system_axi_smc_0} -quiet] -quiet

# IP: bd/led_test_system/ip/led_test_system_rst_ps7_0_50M_0/led_test_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_test_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==led_test_system_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/led_test_system_ooc.xdc
