# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.srcs/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/led_test_system_axi_smc_0.xci
# IP: The module: 'led_test_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/bd_0124.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_1/bd_0124_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_2/bd_0124_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_3/bd_0124_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_4/bd_0124_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_5/bd_0124_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_6/bd_0124_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_7/bd_0124_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_8/bd_0124_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_9/bd_0124_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_10/bd_0124_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_11/bd_0124_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_12/bd_0124_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_1/bd_0124_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_5/bd_0124_s00a2s_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_6/bd_0124_sarn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_7/bd_0124_srn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_8/bd_0124_sawn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_9/bd_0124_swn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_10/bd_0124_sbn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_11/bd_0124_m00s2a_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.srcs/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/led_test_system_axi_smc_0.xci
# IP: The module: 'led_test_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/bd_0124.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_1/bd_0124_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_2/bd_0124_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_3/bd_0124_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_4/bd_0124_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_5/bd_0124_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_6/bd_0124_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_7/bd_0124_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_8/bd_0124_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_9/bd_0124_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_10/bd_0124_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_11/bd_0124_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_12/bd_0124_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_1/bd_0124_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_5/bd_0124_s00a2s_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_6/bd_0124_sarn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_7/bd_0124_srn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_8/bd_0124_sawn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_9/bd_0124_swn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_10/bd_0124_sbn_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/bd_0/ip/ip_11/bd_0124_m00s2a_0_ooc.xdc

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Vivado_Project/LED_Controller/LED_Controller.gen/sources_1/bd/led_test_system/ip/led_test_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
