domain_path: D:\Vivado_Project\LED_Controller\LED_Controller_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\Downloads\Vivado\2025.2.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
